# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@leanprover/infoview-api-0.10.0" = {
      name = "_at_leanprover_slash_infoview-api";
      packageName = "@leanprover/infoview-api";
      version = "0.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@leanprover/infoview-api/-/infoview-api-0.10.0.tgz";
        sha512 = "IN2M5BXf5j3qh6JoqLuqgtl9kpjwH1O4aW2Ey8NQTbkCUhTMKOsGH5LZLIgbCndB4MBVBtQhXwPt1fSW+IxOJw==";
      };
    };
    "@lit-labs/ssr-dom-shim-1.5.0" = {
      name = "_at_lit-labs_slash_ssr-dom-shim";
      packageName = "@lit-labs/ssr-dom-shim";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@lit-labs/ssr-dom-shim/-/ssr-dom-shim-1.5.0.tgz";
        sha512 = "HLomZXMmrCFHSRKESF5vklAKsDY7/fsT/ZhqCu3V0UoW/Qbv8wxmO4W9bx4KnCCF2Zak4yuk+AGraK/bPmI4kA==";
      };
    };
    "@lit/react-1.0.8" = {
      name = "_at_lit_slash_react";
      packageName = "@lit/react";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@lit/react/-/react-1.0.8.tgz";
        sha512 = "p2+YcF+JE67SRX3mMlJ1TKCSTsgyOVdAwd/nxp3NuV1+Cb6MWALbN6nT7Ld4tpmYofcE5kcaSY1YBB9erY+6fw==";
      };
    };
    "@lit/reactive-element-2.1.2" = {
      name = "_at_lit_slash_reactive-element";
      packageName = "@lit/reactive-element";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@lit/reactive-element/-/reactive-element-2.1.2.tgz";
        sha512 = "pbCDiVMnne1lYUIaYNN5wrwQXDtHaYtg7YEFPeW+hws6U47WeFvISGUWekPGKWOP1ygrs0ef0o1VJMk1exos5A==";
      };
    };
    "@types/react-19.2.7" = {
      name = "_at_types_slash_react";
      packageName = "@types/react";
      version = "19.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/react/-/react-19.2.7.tgz";
        sha512 = "MWtvHrGZLFttgeEj28VXHxpmwYbor/ATPYbBfSFZEIRK0ecCFLl2Qo55z52Hss+UV9CRN7trSeq1zbgx7YDWWg==";
      };
    };
    "@types/trusted-types-2.0.7" = {
      name = "_at_types_slash_trusted-types";
      packageName = "@types/trusted-types";
      version = "2.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/trusted-types/-/trusted-types-2.0.7.tgz";
        sha512 = "ScaPdn1dQczgbl0QFTeTOmVHFULt394XJgOQNoyVhZ6r2vLnMLJfBPd53SB52T/3G36VI1/g2MZaX0cwDuXsfw==";
      };
    };
    "@vscode-elements/elements-1.7.1" = {
      name = "_at_vscode-elements_slash_elements";
      packageName = "@vscode-elements/elements";
      version = "1.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vscode-elements/elements/-/elements-1.7.1.tgz";
        sha512 = "3iKAO+B5u/UKXVPOvnlpzFTCCh0lrESgonerNf6EOz2XgnBTBLC01qCHXTXTnFf/foSrcKEnLY7REZOnwZSe3A==";
      };
    };
    "@vscode-elements/react-elements-0.5.0" = {
      name = "_at_vscode-elements_slash_react-elements";
      packageName = "@vscode-elements/react-elements";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vscode-elements/react-elements/-/react-elements-0.5.0.tgz";
        sha512 = "+H1aKuD7uID8Dc/YiQCQUFtGcWxCX+rWH9EIcQTUB1Gj8SfQrwN4Cd46BqQbwJAwtYJkOMl9i+Urfc5mkw8HWw==";
      };
    };
    "@vscode/codicons-0.0.40" = {
      name = "_at_vscode_slash_codicons";
      packageName = "@vscode/codicons";
      version = "0.0.40";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vscode/codicons/-/codicons-0.0.40.tgz";
        sha512 = "R8sEDXthD86JHsk3xERrMcTN6sMovbk1AXYB5/tGoEYCE8DWwya6al5VLrAmQYXC1bQhUHIfHALj8ijQUs11cQ==";
      };
    };
    "csstype-3.2.3" = {
      name = "csstype";
      packageName = "csstype";
      version = "3.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/csstype/-/csstype-3.2.3.tgz";
        sha512 = "z1HGKcYy2xA8AGQfwrn0PAy+PB7X/GSj3UVJW9qKyn43xWa+gl5nXmU4qqLMRzWVLFC8KusUX8T/0kCiOYpAIQ==";
      };
    };
    "es-module-lexer-1.7.0" = {
      name = "es-module-lexer";
      packageName = "es-module-lexer";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-module-lexer/-/es-module-lexer-1.7.0.tgz";
        sha512 = "jEQoCwk8hyb2AZziIOLhDqpm5+2ww5uIE6lkO/6jcOCusfk6LhMHpXXfBLXTZ7Ydyt0j4VoUQv6uGNYbdW+kBA==";
      };
    };
    "es-module-shims-1.10.1" = {
      name = "es-module-shims";
      packageName = "es-module-shims";
      version = "1.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-module-shims/-/es-module-shims-1.10.1.tgz";
        sha512 = "HSSkRLkqFEyX6GrCAHrSOR5iz/QzQJRqZUF7bFJOZ4aoSw0WoSggfsTIGN2yFbF8v6xjQFhT4HGP6b+0qQZmEQ==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "lit-3.3.2" = {
      name = "lit";
      packageName = "lit";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lit/-/lit-3.3.2.tgz";
        sha512 = "NF9zbsP79l4ao2SNrH3NkfmFgN/hBYSQo90saIVI1o5GpjAdCPVstVzO1MrLOakHoEhYkrtRjPK6Ob521aoYWQ==";
      };
    };
    "lit-element-4.2.2" = {
      name = "lit-element";
      packageName = "lit-element";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lit-element/-/lit-element-4.2.2.tgz";
        sha512 = "aFKhNToWxoyhkNDmWZwEva2SlQia+jfG0fjIWV//YeTaWrVnOxD89dPKfigCUspXFmjzOEUQpOkejH5Ly6sG0w==";
      };
    };
    "lit-html-3.3.2" = {
      name = "lit-html";
      packageName = "lit-html";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lit-html/-/lit-html-3.3.2.tgz";
        sha512 = "Qy9hU88zcmaxBXcc10ZpdK7cOLXvXpRoBxERdtqV9QOrfpMZZ6pSYP91LhpPtap3sFMUiL7Tw2RImbe0Al2/kw==";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "react-18.0.0" = {
      name = "react";
      packageName = "react";
      version = "18.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-18.0.0.tgz";
        sha512 = "x+VL6wbT4JRVPm7EGxXhZ8w8LTROaxPXOqhlGyVSrv0sB1jkyFGgXxJ8LVoPRLvPR6/CIZGFmfzqUa2NYeMr2A==";
      };
    };
    "react-fast-compare-3.2.2" = {
      name = "react-fast-compare";
      packageName = "react-fast-compare";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-fast-compare/-/react-fast-compare-3.2.2.tgz";
        sha512 = "nsO+KSNgo1SbJqJEYRE9ERzo7YtYbou/OqjSQKxV7jcKox7+usiUVZOAC+XnDOABXggQTno0Y1CpVnuWEc1boQ==";
      };
    };
    "tachyons-4.12.0" = {
      name = "tachyons";
      packageName = "tachyons";
      version = "4.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tachyons/-/tachyons-4.12.0.tgz";
        sha512 = "2nA2IrYFy3raCM9fxJ2KODRGHVSZNTW3BR0YnlGsLUf1DA3pk3YfWZ/DdfbnZK6zLZS+jUenlUGJsKcA5fUiZg==";
      };
    };
    "vscode-jsonrpc-8.2.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.2.0.tgz";
        sha512 = "C+r0eKJUIfiDIfwJhria30+TYWPtuHJXHtI7J0YlOmKAo7ogxP20T0zxB7HZQIFhIyvoBPwWskjxrvAtfjyZfA==";
      };
    };
    "vscode-languageserver-protocol-3.17.5" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.5.tgz";
        sha512 = "mb1bvRJN8SVznADSGWM9u/b07H7Ecg0I3OgXDuLdn307rl/J3A9YD6/eYOssqhecL27hK1IPZAsaqh00i/Jljg==";
      };
    };
    "vscode-languageserver-types-3.17.5" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.5.tgz";
        sha512 = "Ld1VelNuX9pdF39h2Hgaeb5hEZM2Z3jUrrMgWQAu82jMtZp7p3vJT3BzToKtZI7NgQssZje5o0zryOrhQvzQAg==";
      };
    };
  };
in
{
  "@leanprover/infoview" = nodeEnv.buildNodePackage {
    name = "_at_leanprover_slash_infoview";
    packageName = "@leanprover/infoview";
    version = "0.10.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@leanprover/infoview/-/infoview-0.10.0.tgz";
      sha512 = "Q6Xgh0XSOjZdCf6+NJ46zHPNLXZTjt3y/G+G7GX8WKvnnjFNddssml5yjnU93D4YtCEsYFaLKMSLU3N843QVwQ==";
    };
    dependencies = [
      sources."@leanprover/infoview-api-0.10.0"
      sources."@lit-labs/ssr-dom-shim-1.5.0"
      sources."@lit/react-1.0.8"
      sources."@lit/reactive-element-2.1.2"
      sources."@types/react-19.2.7"
      sources."@types/trusted-types-2.0.7"
      sources."@vscode-elements/elements-1.7.1"
      sources."@vscode-elements/react-elements-0.5.0"
      sources."@vscode/codicons-0.0.40"
      sources."csstype-3.2.3"
      sources."es-module-lexer-1.7.0"
      sources."es-module-shims-1.10.1"
      sources."js-tokens-4.0.0"
      sources."lit-3.3.2"
      sources."lit-element-4.2.2"
      sources."lit-html-3.3.2"
      sources."loose-envify-1.4.0"
      sources."react-18.0.0"
      sources."react-fast-compare-3.2.2"
      sources."tachyons-4.12.0"
      sources."vscode-jsonrpc-8.2.0"
      sources."vscode-languageserver-protocol-3.17.5"
      sources."vscode-languageserver-types-3.17.5"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "An interactive display for the Lean 4 theorem prover.";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
